- name: configure "{{ component }}"
  become: yes
  #hosts: "{{ component }}"
  hosts: localhost
  connection: local
  roles:
  - "{{ component }}"

# ansible-playbook -i inventory.ini -e "component=catalogue" main.yaml